### ISSUE TITLE
Make the number of repos returned configurable with an environment variable

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/gh-latest-repos#4]
Default it to 6 if not specified.

**Comment by yeskunall** [comment]
I kind of want this implemented ASAP so I can use it in one of my projects. I'm guessing you'd want tests for this too? Or can we let this slide without one?

**Comment by sindresorhus** [comment]
It will need a test, yes, but that should be very easy: https://github.com/sindresorhus/gh-latest-repos/blob/5cda67aa4b4b68f0bc340e9d7578b78042a93f3b/test.js#L47-L50
