### ISSUE TITLE
GitHub Repos are not Updating!

### ISSUE THREAD

**Issue by yoginth** [sindresorhus/gh-latest-repos#5]
**Hello**, 
I have deployed this microservice on now.sh after deploying the GitHub Repos are not getting updating (https://yoginth-gh-latest-repos-ddjghetczu.now.sh) I have created tons of Repos, not only me it is not updating on your site too.

**Comment by sindresorhus** [comment]
Note that it updates only once a day. It's updating fine on my site.

**Comment by yoginth** [comment]
Yeah, thank you its working fine! Sorry for the disturbance!
